### ISSUE TITLE
Informix support in idm_db_django

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdb-django#9] opened 2017-06-19 15:34 UTC
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
Hi all.

We are using IDS Cheetah and want to use Django. We found IDS driver for django 
but it is outdated. Will you implement IDS support in Django driver?

Thanks,
Artem.
```

Original issue reported on code.google.com by `gorbl...@gmail.com` on 19 Sep 2012 at 6:26

_Copied from original issue: ibmdb/python-ibmdb#122_

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
Which IDS driver you are talking about. We didn't yet run the Djnago regression 
for IDS.
You are welcome to use our django adaptor, In case of any issue please let us 
know. 
```

Original comment by `rahul.pr...@in.ibm.com` on 21 Sep 2012 at 6:01

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
[deleted comment]
```

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
[deleted comment]
```

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
http://stackoverflow.com/questions/15201584/django-informix-ibm-db-and-db2-data-
server-driver
Is it really done?
```

Original comment by `sthe...@gmail.com` on 4 Mar 2013 at 1:28

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
We don't yet tested our ibm_db_django wrapper with Informix. 

You can give a try to this, in case of any issue let us know.
```

Original comment by `rahul.pr...@in.ibm.com` on 4 Mar 2013 at 2:00

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
Ok.
set DELIMIDENT=y and...
SQL statements came from django in uppercase format, so we got a string like 
> SELECT DISTINCT "ADM_AUDIT"."ACTION" FROM "ADM_AUDIT" 
and get error `The specified table (ADM_AUDIT) is not in the database.`

but names in double quotes (informix treats them like a strings) are responsed 
in lowercase, so
> SELECT DISTINCT "adm_audit"."action" FROM "adm_audit"
works well

```

Original comment by `sthe...@gmail.com` on 4 Mar 2013 at 2:18

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
I find out, that informix version prior 11.70 xc2 do not support case 
insensitive db names and understands only lower-case names. We use (and test) 
informix 11.50 FC6.
```

Original comment by `sthe...@gmail.com` on 4 Mar 2013 at 4:30

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
You can change Upper-case to lower case names generation by modifying 
operation.py file.

At line #176, modify "name = upper( name )" to "name = lower( name )".

```

Original comment by `rahul.pr...@in.ibm.com` on 5 Mar 2013 at 8:11
- Changed state: **Started**

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
Excelent, thanks. And then date problem is rising:

ibm_db_dbi::DataError: Data type format error: time data '07.03.2013 13:55:08' 
does not match format '%Y-%m-%d %H:%M:%S'

```

Original comment by `sthe...@gmail.com` on 5 Mar 2013 at 8:39

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
To avoid this error set GL_DATETIME to '%Y-%m-%d %H:%M:%S', for more 
information you can visit 
http://publib.boulder.ibm.com/infocenter/idshelp/v10/index.jsp?topic=/com.ibm.sq
lt.doc/sqltmst89.htm
```

Original comment by `rahul.pr...@in.ibm.com` on 5 Mar 2013 at 11:09

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
I created a ibm_db_django version that works with Informix to some extent.
https://github.com/nutztherookie/ibm_db_django

Happy for bug-reports.

cheers
```

Original comment by `andr...@nuessle.in` on 2 Jul 2014 at 12:13

**Comment by kadler** [comment] 2017-06-19 15:34
_From @GoogleCodeExporter on March 16, 2015 6:49_

```
Oh and it does work with ./manage.py inspectdb   :)
```

Original comment by `andr...@nuessle.in` on 2 Jul 2014 at 12:18

**Comment by hemlatabhatt** [comment] 2018-02-21 09:39
The issue is resolved,Hence closing .

**Closed by hemlatabhatt** 2018-02-21 09:39 UTC
